# Generated by Django 5.0.2 on 2024-04-25 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="desciption",
            new_name="description",
        ),
    ]
