# Generated by Django 5.0.2 on 2024-04-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_desciption_tasks_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="important",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
